### PR TITLE
Add CODEOWNERS file

### PR DESCRIPTION
**Pull request by truizormeno**
Needed to add code owner names into a file to the root directory.
Screenshot 2022-11-01 at 11 10 52 PM

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Reviewing this right now, let's see...

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Comment by truizormeno** [comment]
> Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

Yes, no problem. Will edit now.

**Review by vanessa-cooper — APPROVED** [review]
Approved! Go ahead and merge this PR. Quickly now.

**Pull request merged**
